# Generated by Django 2.1.7 on 2019-02-22 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('work_position', models.CharField(blank=True, max_length=50)),
                ('date_join', models.DateField(default=datetime.date(2019, 2, 22))),
                ('wage', models.FloatField(default=0.01)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relate_chief', to='manager_employee.Employee')),
            ],
        ),
    ]
