# Generated by Django 2.1.7 on 2019-02-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_join',
            field=models.DateField(default=datetime.date(2019, 2, 24)),
        ),
    ]
